### ISSUE TITLE
Why does DNSRecords require DNSRecord?

### ISSUE THREAD

**Issue by 5t111111** [cloudflare/cloudflare-go#113]
I am not sure why [`DNSRecord` is requried as an argument of `DNSRecords` ](https://github.com/cloudflare/cloudflare-go/blob/0c2ec3079953f72b4bebc68bc9c7a591290fb52b/dns.go#L69), because the zone identifier seems to be enough to specify DNS records which you want to fetch and the use-cases are not documented.

So I always have to pass an empty DNSRecord to acquire DNSRecords of a zone. Could you please let me know why does `DNSRecords` require `DNSRecord`? or it can be removed?

**Comment by jamesog** [comment]
Hi @5t111111,

This is because the Cloudflare API allows you to filter the results returned: https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records

When you pass a `DNSRecord` object, you can populate just some of the fields, e.g. `Type` to just return records of that type, or `Name` to only return records of that name.

Does that makes sense? I agree the documentation needs updating to make this clearer.

**Comment by 5t111111** [comment]
Ah I see. Fair enougn information, thanks!

**Comment by jamesog** [comment]
FWIW I updated the documentation for this in #115 - hopefully it's clearer now. There are examples too, if you read it via `godoc`.
