### ISSUE TITLE
Add "many" version of API calls for UpdateMagicTransitGRETunnels, CreateMagicTransitStaticRoutes & UpdateMagicTransitStaticRoutes

### ISSUE THREAD

**Issue by ivan-section-io** [cloudflare/cloudflare-go#1134]
### Current cloudflare-go version

v0.55.0

### Description

Add "many" version of API calls for UpdateMagicTransitGRETunnels, CreateMagicTransitStaticRoutes & UpdateMagicTransitStaticRoutes.

Only singular versions of these calls are currently available. The http api alreadys supports this calls, but this module doesn't expose it.

### Use cases

Automating create/updates of tunnels and routes with reasonable performance.
Latency introduced by iterating single items is unacceptable when more than several items require create/update.

### Potential cloudflare-go usage

```go
func (api *API) UpdateMagicTransitGRETunnels(ctx context.Context, accountID string, tunnels []MagicTransitGRETunnel) ([]MagicTransitGRETunnel, error) {}

func (api *API) CreateMagicTransitStaticRoutes(ctx context.Context, accountID string, routes []MagicTransitStaticRoute) ([]MagicTransitStaticRoute, error) {}

func (api *API) UpdateMagicTransitStaticRoutes(ctx context.Context, accountID string, routes []MagicTransitStaticRoute) ([]MagicTransitStaticRoute, error) {}
```

### References

Code created to address short-coming. Could become a PR - https://github.com/section/cloudflare-go/pull/1/files

**Comment by jacobbednarz** [comment]
thanks for the issue here, it unfortunately got buried other some other things and fell off my radar. 

for now i think we're going to pass on this given creating and updating single records is the norm within the SDK and we'll wait until such a time that we can automatically support cases like this to avoid snowflake methods from emerging. i'll note this down internally as a potential improvement for these endpoints to track as we progress with the automatically generated solution.

thanks again!

**Comment by ivan-section-io** [comment]
> for now i think we're going to pass on this given creating and updating single records is the norm within the SDK 

For my use case with ~700 of tunnels, ~2,000 routes and updates that often need to change hundreds of tunnels/routes "atomically", updating via a single tunnel/route update calls each taking several/dozens seconds to complete - just isn't practical.
But I also understand this SDK may aim to only address mainstream/trivial use cases, and not the full exposed HTTP API.
