### ISSUE TITLE
I want new api add domain R2 bucket.

### ISSUE THREAD

**Issue by drafdecode** [cloudflare/cloudflare-go#1392]
### Current cloudflare-go version

laster

### Description

I want Cloudflare to create an API to add DNS records of type R2 and also add an API for adding domains in the R2 bucket.

### Use cases

I want Cloudflare to create an API to add DNS records of type R2 and also add an API for adding domains in the R2 bucket.

### Potential cloudflare-go usage

```go
I want Cloudflare to create an API to add DNS records of type R2 and also add an API for adding domains in the R2 bucket.
```

**Comment by jacobbednarz** [comment]
this isn't the place for requesting new APIs as they need to be added and maintained by the service teams. here, we are only adding them to the Go SDK. for R2, you can try using any S3 compatible tool first and if they do the job otherwise, best chance is to drop in a support ticket requesting the specifics.
