### ISSUE TITLE
Align function signatures

### ISSUE THREAD

**Issue by Tenzer** [cloudflare/cloudflare-go#18]
Currently we have a couple of different ways of invoking the functions the library provides. For instance the DNS related functions all take the related zone as a string in the input, the WAF related functions take a zone ID as input and the cache purge and `ZoneDetails()` methods take a `Zone` struct as input.

We should probably come to some conclusion of how we want users to interact with the library, and make sure the functions follow that. It will also make it more clear how the function signatures of future functions will look as we get them implemented.

I am suggesting we take a `Zone` struct as input where possible, it will put the load of looking up the zone on the user, but also means the user is able to cache it however they want, keeping the library leaner and "less magical". Another approach would be to always work on the zone ID, since that is the bare minimum we would need in order to interact with the API. Thoughts?

**Comment by jamesog** [comment]
Initially I wanted as little friction as possible for users of the library/API so thought it made more sense, in most cases, to pass in the zone name and have the function do the zone ID lookup for you. There were one or two cases where it seemed to make more sense to use the object instead.

I do agree that this needs cleaning up and made more consistent.

**Comment by elithrar** [comment]
Q: What benefit does passing `Zone` as the function argument give (today, and in the future) if we require the user to do the name => ID lookup prior?

I 100% agree that rationalizing the function signatures is useful, and would be OK with a functions accepting a `zoneID string` instead of a `zoneName string`.

We can provide a helper function around the API—`ZoneByName(zoneName string) (string, error)` via `GET /zone?name=$name`—that returns the zoneID for the package user to cache locally and then pass to functions as needed.

**Comment by Tenzer** [comment]
Accepting `Zone` instead of a zone ID would mean we could check if the plan of a zone allow an action to be made, without firing a request to the API. That's the only thing I could think of from the top of my head, and may not be enough reason to require users to use `Zone` everywhere.
I think accepting the zone ID as a string would be the best option then.

**Comment by Tenzer** [comment]
This was done in #22.
