### ISSUE TITLE
LB pools and monitors are by default created at the user level although it's also possible to create them at the Organisation level

### ISSUE THREAD

**Issue by stephane-cloudflare** [cloudflare/cloudflare-go#184]
Looking at the Function that creates a pool or a monitor, I see that the API path is hardcoded to be `/user` which is not good since as user belonging to an ORG wouldn't be able to create a Load balancer on a zone of this same ORG as the it wouldn't see the pools created at the user level.

We should add as a parameter the ORG the user is targeting for the pool or monitors creation.

https://github.com/cloudflare/cloudflare-go/blob/1f9007fbecae20711133c60519338c41cef1ffb4/load_balancing.go#L111

**Comment by garrettgalow** [comment]
we need to add support to specify an account. we can either make it an additional option to specify the account or we can just move the endpoint to always use account. While the latter is a breaking change I think I rather us do that in order to bring this up to date with how the API should be used.

cc @patryk , @zackproser

**Comment by gofish** [comment]
It may be confusing given the name of the unexported function `userBaseURL`, but that method will in fact use the `/account/...` base url if the `OrganizationID` field is set on the API client.
