### ISSUE TITLE
flarectl dns create-or-update doesn't support root records

### ISSUE THREAD

**Issue by colbin8r** [cloudflare/cloudflare-go#206]
The `flarectl dns create-or-update` can only update subdomain records, not records for the root domain. For instance, creating-or-updating `sub.example.com` is possible, but not `example.com`. If you run something like:

```sh
$ ./flarectl dns create-or-update --zone=example.com --name=example.com --content=1.2.3.4 --type=A
```

`flarectl` will create a new `example.com.example.com` record. I belive the issue is here:
https://github.com/cloudflare/cloudflare-go/blob/1e1d4e0b8ae7aad64146f9f8f6a366209ce39e8b/cmd/flarectl/dns.go#L90-L92

where the name of the record should be `name`, not `name + "." + zone`.

This behavior would be consistent with the `dns create` and `dns update` commands, which can create root records.

**Comment by digitalsparky** [comment]
+1 this is a really silly oversight and needs to be resolved, works perfectly fine with create.

**Comment by zoopster** [comment]
No one wants to make this simple fix?

**Comment by colbin8r** [comment]
@zoopster It looks like there was some discussion on it and the work has been abandon: https://github.com/cloudflare/cloudflare-go/pull/268#issuecomment-458807315

**Comment by joepurdy** [comment]
@zoopster yep, I abandoned the work for fixing this issue because the initial work was a [naive fix at best](https://github.com/cloudflare/cloudflare-go/pull/268/commits/3f9ce69ed3c5b240559f1ab7e0cd41d270813684) and properly addressing the issue fell off my radar.

Feel free to fork and take a shot at it. There's discussion in the linked PR that got closed out to guide you in implementing a more robust fix!
