### ISSUE TITLE
invalid credentials: key & email must not be empty

### ISSUE THREAD

**Issue by DeathStarName** [cloudflare/cloudflare-go#251]
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/cloudflare/cloudflare-go"
)

func main() {
	// Construct a new API object
	api, err := cloudflare.New(os.Getenv("<TOKEN>"), os.Getenv("deathstar@deathstar.name"))
	if err != nil {
		log.Fatal(err)
	}

	// Fetch user details on the account
	u, err := api.UserDetails()
	if err != nil {
		log.Fatal(err)
	}
	// Print user details
	fmt.Println(u)

	// Fetch the zone ID
	id, err := api.ZoneIDByName("deathstar.name") // Assuming example.com exists in your Cloudflare account already
	if err != nil {
		log.Fatal(err)
	}

	// Fetch zone details
	zone, err := api.ZoneDetails(id)
	if err != nil {
		log.Fatal(err)
	}
	// Print zone details
	fmt.Println(zone)
}

give error 2018/11/17 02:58:14 invalid credentials: key & email must not be empty
exit status 1
why? 
tested on MacOs and FreeBSD

**Comment by jacobbednarz** [comment]
Afternoon @DeathStarName!

The issue here is that you're not instantiating the client with your credentials (and misusing Go [`os.Getenv()`](https://golang.org/pkg/os/#Getenv) in the process). You have the following:

```go
func main() {
// ..
api, err := cloudflare.New(os.Getenv(""), os.Getenv("deathstar@deathstar.name"))
// ..
```

[`New()`](https://github.com/cloudflare/cloudflare-go/blob/129166671c6ecb20c071c24004aa98f9aa0cdb8a/cloudflare.go#L78-L93) requires two string parameters; one for the API key and the other for the email address. In your code, you're using `os.Getenv` which accepts the name of an environment variable key and fetches the value. Your first usage of it isn't looking up any value (`os.Getenv("")`) and your second usage is looking in the environment for a key of "deathstar@deathstar.name" which I assume is your email address, not environment variable key name so that is going to return nothing as well.

There are a couple of ways you could fix this. 

- You can set your credentials as strings.

  ```go
  api, err := cloudflare.New("API_KEY_HERE", "EMAIL_ADDRESS_HERE")
  ```

  This isn't a recommended approach however it is fine if you don't intend to publish the code anywhere and it will remain local to your machine.

- You can pull your credentials from the environment.

  ```go
  api, err := cloudflare.New(os.Getenv("CF_API_KEY"), os.Getenv("CF_EMAIL_ADDRESS"))
  ```

  And invoke the script with `CF_API_KEY="key here" CF_EMAIL_ADDRESS="email here" go run main.go`

However, before doing either of those, I would recommend you check out some guides on programming in Go ([A Tour of Go](https://gobyexample.com/) and [Go By Example](https://gobyexample.com/) are two I usually recommend) to help you get a grasp on the core concepts before diving into using a library like this one.

**Comment by DeathStarName** [comment]
> Afternoon @DeathStarName!
> 
> The issue here is that you're not instantiating the client with your credentials (and misusing Go [`os.Getenv()`](https://golang.org/pkg/os/#Getenv) in the process). You have the following:
> 
> ```go
> func main() {
> // ..
> api, err := cloudflare.New(os.Getenv(""), os.Getenv("deathstar@deathstar.name"))
> // ..
> ```
> 
> [`New()`](https://github.com/cloudflare/cloudflare-go/blob/129166671c6ecb20c071c24004aa98f9aa0cdb8a/cloudflare.go#L78-L93) requires two string parameters; one for the API key and the other for the email address. In your code, you're using `os.Getenv` which accepts the name of an environment variable key and fetches the value. Your first usage of it isn't looking up any value (`os.Getenv("")`) and your second usage is looking in the environment for a key of "[deathstar@deathstar.name](mailto:deathstar@deathstar.name)" which I assume is your email address, not environment variable key name so that is going to return nothing as well.
> 
> There are a couple of ways you could fix this.
> 
> * You can set your credentials as strings.
>   ```go
>   api, err := cloudflare.New("API_KEY_HERE", "EMAIL_ADDRESS_HERE")
>   ```
>   
>   
>   This isn't a recommended approach however it is fine if you don't intend to publish the code anywhere and it will remain local to your machine.
> * You can pull your credentials from the environment.
>   ```go
>   api, err := cloudflare.New(os.Getenv("CF_API_KEY"), os.Getenv("CF_EMAIL_ADDRESS"))
>   ```
>   
>   
>   And invoke the script with `CF_API_KEY="key here" CF_EMAIL_ADDRESS="email here" go run main.go`
> 
> However, before doing either of those, I would recommend you check out some guides on programming in Go ([A Tour of Go](https://gobyexample.com/) and [Go By Example](https://gobyexample.com/) are two I usually recommend) to help you get a grasp on the core concepts before diving into using a library like this one.

I insert the key. I just removed it from the code that showed.

**Comment by DeathStarName** [comment]
func main() {
// ..
api, err := cloudflare.New(os.Getenv("MY API KEY"), os.Getenv("deathstar@deathstar.name"))
// ..

**Comment by jacobbednarz** [comment]
Please re-read my comment above as it outlines your issue and why your
credentials aren't being set resulting in the error message.
