### ISSUE TITLE
List certificate pack is unusable in V2

### ISSUE THREAD

**Issue by whs** [cloudflare/cloudflare-go#2744]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

2.3.0

### Go environment

GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/whs/.cache/go-build'
GOENV='/home/whs/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/whs/go/pkg/mod'
GONOPROXY='<private>'
GONOSUMDB='<private>'
GOOS='linux'
GOPATH='/home/whs/go'
GOPRIVATE='<private>'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/nix/store/vz8d6wmfcf38l3h3vymwqr6c5zxp5jmp-go-1.22.3/share/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/nix/store/vz8d6wmfcf38l3h3vymwqr6c5zxp5jmp-go-1.22.3/share/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='<private>/cloudflare-cert-renewal/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3013455866=/tmp/go-build -gno-record-gcc-switches'

### Expected output

It should return something usable

### Actual output

It is a stub https://github.com/cloudflare/cloudflare-go/blob/v2/ssl/certificatepack.go#L211

### Code demonstrating the issue

packs := d.cloudflare.SSL.CertificatePacks.ListAutoPaging(ctx, ssl.CertificatePackListParams{
    ZoneID: cloudflare.String(zone.ID),
})

### Steps to reproduce

See the return value type of that code

### References

I tried using v0 but the API https://developers.cloudflare.com/api/operations/ssl-verification-edit-ssl-certificate-pack-validation-method is also unavailable

**Comment by jacobbednarz** [comment]
this looks to be a bit of confusion as to what is meant to happen here. 

the link you've provided is only the type, it doesn't have any bearing on the method itself working (or being cast/used as JSON or an interface with inner fields). you're right that the struct is bare, but it definitely usable using the `Result` from `List` instead.

to get this working, you can try the following

```
certs, _ := client.SSL.CertificatePacks.List(context.TODO(), ssl.CertificatePackListParams{
		ZoneID: cloudflare.F("0da42c8d2132a9ddaf714f9e7c920711"),
		Status: cloudflare.F(ssl.CertificatePackListParamsStatusAll),
	})

	fmt.Println(fmt.Sprintf("%#v", certs.Result))
```

(note: using `List` here, not `ListAutoPaging`)

what you're seeing here with `ListAutoPaging` only returning a `SinglePage` type is that the pagination isn't correctly defined for the endpoint here so we can only return a single page a the endpoint isn't instructing the SDK how to move to the next page. if you want, you can use `List` in conjunction with `GetNextPage` to fetch all the results and append them to another map in the meantime. alternatively, you can use the `client.Get` method to make a raw HTTP call to the endpoint and do the pagination yourself.

the internal team is already tracking this as an improvement so i'm going to close this off here since it's not a SDK specific issue. once the endpoint is updated, this will be automatically pulled into all the SDKs.
