### ISSUE TITLE
DNS  - UpdateDNSRecord Change Record Type

### ISSUE THREAD

**Issue by Evesy** [cloudflare/cloudflare-go#278]
Provide a general summary of the issue in the title above. You can also
remove any sections you don't need along with all of the section
descriptions before submitting.

## Expected behavior

The Cloudflare API supports changing the type on an existing record (i.e. A record to CNAME). A simple example would be patching an existing A record with the below to make it a TXT record:

```json
{
 "type": "TXT"
}
```

## Current behavior

Despite what's specified in the DNS record as the new desired state, the type is overwritten by the type of the existing record (https://github.com/cloudflare/cloudflare-go/blob/master/dns.go#L144)

## Steps to reproduce (for bugs)

Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant.

1. Create DNS record e.g. the below:
```go
cloudflare.DNSRecord{
    Type:     "A",
    Name:     "example",
    Content:  "4.4.4.4",
    Proxied:  false,
    ZoneName: domain,
    ZoneID:   zoneId,
    TTL:      3600,
}
```
2. Update the DNS record with the below:
```go
cloudflare.DNSRecord{
    Type:     "TXT",
    Content:  "8.8.8.8",
}
```
3. The Content is successfully updated to `8.8.8.8`, however the record type remains unchanged.

There might be a reason for this logic however I'd expect to be able to _attempt_ to change the record type via an update and receive an error if any fields are invalid.

* Version used (e.g. git sha or specific tag): Master branch (Last commit: https://github.com/cloudflare/cloudflare-go/commit/9837a599c0ba49ff8208dd679b4500e8ece407a5)
* Environment name and version (e.g. Go 1.11, MacOS 10.14.1): Go 1.11.4 darwin/amd64

**Comment by jacobbednarz** [comment]
I'm a little uncertain whether you _should_ be doing this as DNS records aren't a 1:1 match and you could end up in a situation where you have dangling attributes (since it's a PATCH operation and not a full replacement). IIRC, `UpdateDNSRecord` should only be used for the same record type whereas if you're swapping the type, I would say to create the new one and delete the old one.

For example, in the Terraform provider (which uses this library under the hood), we actually [force creation of a new resource if the `type` value is changed](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/b193a2d872da09cb5426c9ccad64e41de8bc7611/cloudflare/resource_cloudflare_record.go#L48-L52) to prevent unnecessary updates.

**Comment by Evesy** [comment]
Thanks for the clarification, all makes sense 👍Delete/Recreate it is
