### ISSUE TITLE
Add User Agent header to requests 

### ISSUE THREAD

**Issue by zackproser** [cloudflare/cloudflare-go#296]
The cloudflare-go library should identify itself with a user agent header that contains the library name and version.

**Comment by jacobbednarz** [comment]
Looks like we [already](https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L38) have the UserAgent defined on the API struct (and a [configuration option](https://github.com/cloudflare/cloudflare-go/blob/04dbec91dcf2207da1e14dddc14d357ab24aa7bc/options.go#L76-L85) for setting it). Do you just intend to use a better default like `cloudflare-go (git 92c7560)` or `cloudflare-go (1.1.0)` instead of the generic Go HTTP useragent?

+1 on this regardless on the approach.

**Comment by jacobbednarz** [comment]
FWIW, the [terraform provider does this](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/provider.go#L183) too.

**Comment by zackproser** [comment]
Thanks @jacobbednarz! Indeed - filed this in a hurry, but we could use a more useful default like ```cloudflare-go 1.1.0```
