### ISSUE TITLE
Implement missing Zone endpoints

### ISSUE THREAD

**Issue by Tenzer** [cloudflare/cloudflare-go#37]
https://api.cloudflare.com/#zone

**Comment by jamesog** [comment]
I've managed to add all but `CreateZone` and `EditZone`. These are slightly bamboozling me at the moment.

`CreateZone`, at a minimum, just needs to take a name (string), however can also take a jump_start (bool) and an organization ID (optionally with name but I don't think we need that). The bit that is throwing me here is the organization - if I use the Organization type (or any struct type), you can't pass a `nil` to the function if you're not adding to an organization.

I was considering creating a `NewZone` struct but it will always end up having an empty `Organization` field if no org is specified. What's the best thing to do here?

`EditZone` has me similarly stumped because you can only specify one of `paused`, `vanity_name_servers` or `plan`.

**Comment by elithrar** [comment]
Suggestions:

```go
type CreateZoneOptions
    OrganizationID string
    // Room for growth later
}

func (api *API) CreateZone(zoneName string, jumpStart bool, orgID string) (*ZoneResponse, error)`
```

* Makes it explicit
* Not perfect as you have to pass a `""` if you don't have an `orgID`
* Gets a little lengthy

I don't think variadic or functional options are appropriate here. The alternative would be to have:

```go
type ZoneOptions
    OrganizationID string
    // Room for growth later
}

func (api *API) CreateZone(zoneName string, jumpStart bool, opts *ZoneOptions) (*ZoneResponse, error)`
```

* Extensible in the future
* Downside: you pass `nil` when you have no further options (not ideal, but not the worst thing in the world)

Is EditZone *one of* only? https://api.cloudflare.com/#zone-edit-zone-properties

**Comment by jamesog** [comment]
I think it may still be required to have a type generated inside `CreateZone` based on whether the orgID is present or not - if it wasn't defined we don't want to send an empty to the API.

For example, if orgID wasn't specified:

```go
type ZoneOptions struct {
  Name string `json:"name"`
  JumpStart bool `json:"jump_start"`
  OrganizationID string `json:"organization_id"`
}

opts := ZoneOptions{
  Name: "foo",
  JumpStart: true,
}
```

will generate the JSON:

```json
{"name": "foo", "jump_start": true, "organization_id": ""}
```

instead of 

```json
{"name": "foo", "jump_start": true}
```

EditZone is certainly confusing. I _think_ it's just those three options.

**Comment by elithrar** [comment]
`OrganizationID string `json:"organization_id,omitempty"` should do the trick

**Comment by jamesog** [comment]
I figured out `CreateZone` as per the PR, but `EditZone` is still bamboozling me somewhat. You can only set one of the three options - this bit I can deal with via `,omitempty` in the struct, but I'm trying to figure out how to make sure only one option is set.

At the moment I'm thinking to either create setter methods on a new `ZoneOptions` struct that check and/or clear other fields in the struct, or perhaps just plain old functions that directly call the `PATCH` endpoint. The latter might be better. Thoughts?

**Comment by jamesog** [comment]
To clarify the last comment if I went with "plain old functions" it'd probably look like this:

```go
type ZoneOptions struct {
    Paused bool `json:"paused,omitempty"`
    VanityNS []string `json:"vanity_name_servers,omitempty"`
    Plan *ZonePlan `json:"plan,omitempty"`
}

func ZoneSetPaused(zoneID string, paused bool) {
    zoneopts := ZoneOptions{Paused: paused}
    api.EditZone(zoneID, zoneopts)
}

func (api *API) EditZone(zoneID string, props ZoneOptions) (Zone, error) {
    // Call PATCH /zones/zoneid
    ...
}
```

**Comment by jamesog** [comment]
This is all done except for an issue with zone settings - you can pause a zone but can't unpause right now.

**Comment by jamesog** [comment]
This is done in #65.
