### ISSUE TITLE
UpdateDNSRecord reverts proxied status

### ISSUE THREAD

**Issue by adrianrudnik** [cloudflare/cloudflare-go#563]
## Expected behavior

Updating an IP address with a simple

```go
api.UpdateDNSRecord(zoneId, recordId, cf.DNSRecord{Content: ip.String()})
```

is expected to update the IP adress only, right? Looking at the internals PATCH is used, not PUT.

## Current behavior

As the parameter given to `UpdateDNSRecord` is a `DNSRecord` struct, with `Proxied bool`, it will default to `false` even if the proxied status is currently `true`. Triggering the update request above will revert the proxied status back to `false`. This seems to affect `priority` as well.

## Possible solution

I'm not sure what the correct approach is, do you need to supply

1. the full `DNSrecord` to `UpdateDNSRecord`? But then why is that method fetching the current status itself from the API and overwriting `Name` and `Type`, but not `Proxied`?
2. the changed fields only from a  `DNSRecord`? Can this even work when the whole [struct is marshaled](https://play.golang.org/p/SXn3ogYwxzP) for a simple PATCH?

Right now 1. seems like the only solution, but that would require me to trigger a `api.DNSRecord()` beforehand and than have the `UpdateDNSRecord` just do the same call again, hitting the API twice for no good reason.

## Context

Updating an A DNS entry to a new IP address when a dependency announces a change. Something like DynDNS.

## Your Environment

* github.com/cloudflare/cloudflare-go v0.13.6
* go version go1.15.4 linux/amd64

**Comment by jacobbednarz** [comment]
As the functionality stands, the [`UpdateDNSRecord`}(https://github.com/cloudflare/cloudflare-go/blob/59bf1c5c68112f000b75ea1dd0d55644836f5580/dns.go#L134) already performs a fetch of the initial record to compare/mutate on your behalf.

https://github.com/cloudflare/cloudflare-go/blob/59bf1c5c68112f000b75ea1dd0d55644836f5580/dns.go#L135-L146

The issue here seems to be that:

1. Those conditionals aren't set for all fields (specifically a boolean here that defaults off); and
2. The endpoint accepts PATCH with optional fields however the library makes it act more like a PUT. 

Looking through the history, it looks like it was initially added as a [PUT request](https://github.com/cloudflare/cloudflare-go/commit/96e9d81c400378fd0d6a67d32861ce0650710ed7) however a couple of years ago, the method was [swapped to PATCH](https://github.com/cloudflare/cloudflare-go/commit/a80236a02adfc1fc95be394d3bc5ddf1501caa34b) without any other changes. There isn't any context with the commit itself however I also recall the PUT request wasn't quite working as intended so a PATCH with all fields was a preferred approach. The API does have documentation for both so we could potentially make the changes however I suspect the default values will still be an issue for you. 

@patryk do you have a preference here? I'm leaning towards adding in the conditional to handle the default values (`proxied` mainly) in order to solve this one.

**Comment by patryk** [comment]
I originally changed PUT to PATCH in hope that it would alleviate situations like these. And largely it did.
But it seems still `Proxied` and `Priority` are missing `omitempty`.
https://github.com/cloudflare/cloudflare-go/blob/20d8c262f09e199dcef2c70039cc737e0505c0fb/dns.go#L19

The backend when receiving PATCH request merges incoming values with saved ones. Because `Proxied` and `Priority` are always sent, they will be overridden with defaults.

I think putting missing `omitempty` will be most optimal, with no need to add extra conditions.
