### ISSUE TITLE
Feature request: Add page rules

### ISSUE THREAD

**Issue by ferraro** [cloudflare/cloudflare-go#602]
Please add pagerules.

## Expected behavior
flarectl pagerules add "http://www.mysite.tld/*" "Always Use HTTPS" --zone mysite.tld

If you're describing a bug, tell us what should happen.
If you're suggesting a change/improvement, tell us how it should work.

## Current behavior
No help topic for 'add'

## Possible solution
Please implement support to add page rules.

**Comment by jacobbednarz** [comment]
I'm sorry but I can't imagine page rules being integrated into flarectl as is due to the compexity of some of the conditions. I'll add this to an ongoing discussion internally and report back if anything changes. 

In the meantime, if you're looking to programmatically manage page rules, I'd recommend checking out [Terraform](https://github.com/cloudflare/terraform-provider-cloudflare) instead.
