### ISSUE TITLE
Improve ReadWorkersKV to not return error when key not found

### ISSUE THREAD

**Issue by OilyLime** [cloudflare/cloudflare-go#744]
### Current cloudflare-go version

v0.27.0

### Description

Given that KV is a kv-database with optional TTLs, it is natural to expect some lookups to fail. That said, the default behaviour for a "miss" from the API is to return a 404, which then gets returned as a `APIRequestError` -- this is less than optimal UX in my opinion, since lookup misses are an _expected_ error.

### Use cases

Building an application that interacts with KV via the API, we expect some keys to miss, but don't want to handle that as an error.

### Potential cloudflare-go usage

```go
b, found, err := api.ReadWorkersKV(ctx, namespace, key)
if err != nil {
    fmt.Printf("error while reading KV, %v", err)
    os.Exit(1)
}
if !found {
    fmt.Println("KV key not found")
    os.Exit(0)
}
var myFoo Foo
json.Unmarshal(b, &myFoo)
```

**Comment by jacobbednarz** [comment]
this is a reasonable suggestion however, as it would break the existing method signature, we probably won’t land this immediately until we assess more of it’s usage downstream in tools like the Terraform provider. instead, I would recommend you use the result of the `err` to check if the message contains the not found string and handle your logic appropriately there for now as it would work the same as introducing the method signature change you’ve proposed.

**Comment by jacobbednarz** [comment]
thanks for your patience 🙇 

since this issue was raised, the error handling has improved and 404s should now be an explicit [`NotFoundError`](https://github.com/cloudflare/cloudflare-go/blob/master/errors.go#L231-L258). an [example](https://github.com/cloudflare/terraform-provider-cloudflare/blob/daba7ace42ee263b12a988dabbbe766b8de935fa/internal/provider/resource_cloudflare_access_application.go#L104-L112) of using this can be found in the terraform-provider-cloudflare repository.

i'm closing this one out now as that should work without modifying the signature and matching the conventions we'll likely be taking with these scenarios going forward.
